# Generated by Django 3.2.9 on 2022-04-05 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mytodo', '0003_alter_todo_todo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
